apiVersion: v1
kind: Service
metadata:
  name: wapi-service
spec:
  selector:
    app: wapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort  # Change to 'ClusterIP' if you don't need external access
  