apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapi-deployment
  annotations:
    instrumentation.opentelemetry.io/inject-nodejs: "openobserve-collector/openobserve"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wapi-app
  template:
    metadata:
      labels:
        app: wapi-app
    spec:
      containers:
        - name: wapi-container
          image: meghap123/wapi:5
          ports:
            - containerPort: 3000
