apiVersion: v1
kind: Service
metadata:
  name: mapi-service
spec:
  selector:
    app: mapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort  # Change to 'ClusterIP' if you don't need external access
  